### PR TITLE
Change folders name and static file paths

### PR DESCRIPTION
**Pull request by renancarvalho**
@andersonaguiar , @chiefGui and @zigolis.

This PR changes the folder name (just using numbers for a while), and changed static files path.
It is also a refactoring of the routes.js file.

What do you guys think ?

### CODE REVIEW

**Comment by chiefGui** [comment]
Way better. :+1:

**Comment by andersonaguiar** [comment]
Great! :ok_hand:

**Comment by zigolis** [comment]
Guys, in my humble opinion it's really import for beginners to read in some place what they are learning, even we write this information in another place.

Try put yourself in beginners shoes, a regular structure called 01/ 02/ 03/ does not meaning anything for them.

So, I think we should put this kind of information [01 - initialize, 02 - el...] in some else place.

Ideas?

**Comment by renancarvalho** [comment]
@zigolis I agree, I think that we could use the current html file to explain whats going on.

**Comment by andersonaguiar** [comment]
I think we should create a home page with a menu for the user can navigates easier.

Changing the name folders to: 01 - Initialize, 02 - render, etc. We can pass two parameters on URL: id and name.

Sounds good for you?

**Comment by chiefGui** [comment]
I think we should to care more about creating a good documentation, such as creating a home page like @andersonaguiar suggested than naming folders to be intuitive.

We are programmers. Numbers shouldn't be our enemies.

By the bye, I also think that cost us nothing renaming the folders to be friendlier. So, I think I agree with everyone. What's the conclusion, after all?

**Comment by renancarvalho** [comment]
@chiefGui if we rename the folders name will break here:

https://github.com/BackboneJsBrasil/Backbone4Dummies/pull/1/files#diff-2b246251392c8f9e0ee2a467cb8ab34cR6

We'll need to refactor if we decide to change the folders name

**Comment by chiefGui** [comment]
We can switch for slugs. Instead of having numbers, let's use `initialize`, `delete-articles`, etc. Then, in the API, just change from `:id` to `:slug` and voi là!

**Comment by renancarvalho** [comment]
:+1:

**Comment by zigolis** [comment]
Hey guys,

We can build a homepage with a beautiful and simple design as @andersonaguiar suggested and in this page we can put a menu (talking about node now), passing two parameters for our api (:id and :name).

It's an option for our case, I really think it's super important put names or anything else for describe the examples, thinks it guys, it's a "small course for dummies".

We are developers, creating this course, we have to becomes this easier for them instead of becomes easier for us.

Bjundas

**Comment by renancarvalho** [comment]
I changed the names.

**Pull request merged**
